inherit_from: .rubocop.yml

AllCops:
  Include:
    - bundler/**/*.rb
    - bundler/**/*.gemspec
    - bundler/**/Rakefile
    - bundler/**/Gemfile
    - bundler/**/*.rake
    - bundler/**/Executable
    - bundler/**/Executable.*
  Exclude:
    - bin/*
    - pkg/**/*
    - tmp/**/*
    - util/**/*
    - bundler/tmp/**/*
    - bundler/lib/bundler/vendor/**/*


# Lint

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DuplicateCaseCondition:
  Enabled: true

Lint/EmptyExpression:
  Enabled: true

Lint/NonLocalExitFromIterator:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/ReturnInVoidContext:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/Void:
  Enabled: true

# Layout

Layout/EmptyLineAfterMagicComment:
  Enabled: true

# Naming

Naming/BlockParameterName:
  Enabled: true

Naming/ConstantName:
  Enabled: true

Naming/MethodName:
  Enabled: true

Naming/VariableName:
  Enabled: true

Naming/VariableNumber:
  Enabled: true

# Performance

Performance/RegexpMatch:
  Enabled: true

# Style

Style/AsciiComments:
  Enabled: true

Style/BarePercentLiterals:
  Enabled: true

Style/CharacterLiteral:
  Enabled: true

Style/ClassCheck:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/ColonMethodCall:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/DoubleNegation:
  Enabled: true

Style/EmptyCaseCondition:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/FormatString:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# 1.8.7 support
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: hash_rockets

Style/IdenticalConditionalBranches:
  Enabled: true

Style/IfUnlessModifierOfIfUnless:
  Enabled: true

Style/LineEndConcatenation:
  Enabled: true

Style/MultilineMemoization:
  Enabled: true

Style/MultilineTernaryOperator:
  Enabled: true

Style/MultipleComparison:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/NestedModifier:
  Enabled: true

Style/NestedParenthesizedCalls:
  Enabled: true

Style/Next:
  Enabled: true

Style/NonNilCheck:
  Enabled: true

Style/NumericLiterals:
  Enabled: true

Style/NumericLiteralPrefix:
  Enabled: true

Style/OrAssignment:
  Enabled: true

Style/ParallelAssignment:
  Enabled: true

Style/ParenthesesAroundCondition:
  Enabled: true

Style/PreferredHashMethods:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantInterpolation:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/RedundantSortBy:
  Enabled: true

Style/RegexpLiteral:
  Enabled: true

Style/RescueModifier:
  Enabled: true

Style/RescueStandardError:
  Enabled: true

Style/SelfAssignment:
  Enabled: true

Style/Semicolon:
  Enabled: true

Style/SingleLineMethods:
  Enabled: true

Style/StabbyLambdaParentheses:
  Enabled: true

Style/StderrPuts:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/TernaryParentheses:
  Enabled: true

Style/UnlessElse:
  Enabled: true

Style/YodaCondition:
  Enabled: true
