inherit_from: .rubocop.yml

AllCops:
  Include:
    - bundler/**/*.rb
    - bundler/**/*.gemspec
    - bundler/**/Rakefile
    - bundler/**/Gemfile
    - bundler/**/*.rake
    - bundler/**/Executable
    - bundler/**/Executable.*
  Exclude:
    - bin/*
    - pkg/**/*
    - tmp/**/*
    - util/**/*
    - bundler/tmp/**/*
    - bundler/lib/bundler/vendor/**/*


# Lint

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DuplicateCaseCondition:
  Enabled: true

Lint/EmptyExpression:
  Enabled: true

Lint/NonLocalExitFromIterator:
  Enabled: true

Lint/RedundantStringCoercion:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/ReturnInVoidContext:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UselessAccessModifier:
  Enabled: true

Lint/Void:
  Enabled: true

# Layout

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/ConditionPosition:
  Enabled: true

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

Layout/EmptyComment:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLinesAroundArguments:
  Enabled: true

Layout/EmptyLinesAroundBeginBody:
  Enabled: true

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/AssignmentIndentation:
  Enabled: true

Layout/FirstArgumentIndentation:
  Enabled: true

Layout/InitialIndentation:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: true

Layout/MultilineArrayBraceLayout:
  Enabled: true

Layout/MultilineBlockLayout:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true

Layout/SpaceBeforeComma:
  Enabled: true

Layout/SpaceBeforeComment:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: true

Layout/SpaceBeforeSemicolon:
  Enabled: true

Layout/SpaceInLambdaLiteral:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Layout/SpaceInsideArrayPercentLiteral:
  Enabled: true

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: true

Layout/SpaceInsideRangeLiteral:
  Enabled: true

Layout/SpaceInsideReferenceBrackets:
  Enabled: true

Layout/SpaceInsideStringInterpolation:
  Enabled: true

Layout/IndentationStyle:
  Enabled: true

# Naming

Naming/AsciiIdentifiers:
  Enabled: true

Naming/BinaryOperatorParameterName:
  Enabled: true

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/ConstantName:
  Enabled: true

Naming/FileName:
  Enabled: true
  Exclude:
    - 'bundler/spec/realworld/fixtures/warbler/bin/warbler-example.rb'

Naming/MethodName:
  Enabled: true

Naming/BlockParameterName:
  Enabled: true

Naming/VariableName:
  Enabled: true

Naming/VariableNumber:
  Enabled: true

# Performance

Performance/Casecmp:
  Enabled: true

Performance/Count:
  Enabled: true

Performance/DoubleStartEndWith:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/TimesMap:
  Enabled: true

# Style

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

Style/ArrayJoin:
  Enabled: true

Style/AsciiComments:
  Enabled: true

Style/Attr:
  Enabled: true

Style/BarePercentLiterals:
  Enabled: true

Style/BeginBlock:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/CharacterLiteral:
  Enabled: true

Style/ClassCheck:
  Enabled: true

Style/ClassMethods:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/ColonMethodCall:
  Enabled: true

Style/ColonMethodDefinition:
  Enabled: true

Style/CommandLiteral:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/DoubleNegation:
  Enabled: true

Style/EachForSimpleLoop:
  Enabled: true

Style/EmptyBlockParameter:
  Enabled: true

Style/EmptyCaseCondition:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/EmptyLambdaParameter:
  Enabled: true

Style/EndBlock:
  Enabled: true

Style/EvenOdd:
  Enabled: true

Style/For:
  Enabled: true

Style/FormatString:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# 1.8.7 support
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: hash_rockets

Style/IdenticalConditionalBranches:
  Enabled: true

Style/IfUnlessModifierOfIfUnless:
  Enabled: true

Style/IfWithSemicolon:
  Enabled: true

Style/InfiniteLoop:
  Enabled: true

Style/LambdaCall:
  Enabled: true

Style/LineEndConcatenation:
  Enabled: true

Style/MinMax:
  Enabled: true

Style/MixinGrouping:
  Enabled: true

Style/MultilineMemoization:
  Enabled: true

Style/MultilineTernaryOperator:
  Enabled: true

Style/MultipleComparison:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/NestedModifier:
  Enabled: true

Style/NestedParenthesizedCalls:
  Enabled: true

Style/NestedTernaryOperator:
  Enabled: true

Style/Next:
  Enabled: true

Style/NonNilCheck:
  Enabled: true

Style/NumericLiteralPrefix:
  Enabled: true

Style/NumericLiterals:
  Enabled: true

Style/OneLineConditional:
  Enabled: true

Style/OptionalArguments:
  Enabled: true

Style/OrAssignment:
  Enabled: true

Style/ParallelAssignment:
  Enabled: true

Style/ParenthesesAroundCondition:
  Enabled: true

Style/PercentQLiterals:
  Enabled: true

Style/PreferredHashMethods:
  Enabled: true

Style/Proc:
  Enabled: true

Style/RandomWithOffset:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantConditional:
  Enabled: true

Lint/RedundantCopDisableDirective:
  Enabled: true

Lint/RedundantCopEnableDirective:
  Enabled: true

Style/RedundantException:
  Enabled: true

Style/RedundantInterpolation:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/RedundantSortBy:
  Enabled: true

Lint/RedundantSplatExpansion:
  Enabled: true

Style/RegexpLiteral:
  Enabled: true

Style/RescueModifier:
  Enabled: true

Style/RescueStandardError:
  Enabled: true

Style/Sample:
  Enabled: true

Style/SelfAssignment:
  Enabled: true

Style/Semicolon:
  Enabled: true

# We adopted raise instead of fail.
Style/SignalException:
  Enabled: true
  EnforcedStyle: only_raise

Style/SingleLineMethods:
  Enabled: true

Style/StabbyLambdaParentheses:
  Enabled: true

Style/StderrPuts:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Strip:
  Enabled: true

Style/StructInheritance:
  Enabled: true

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/SymbolLiteral:
  Enabled: true

Style/SymbolProc:
  Enabled: true

Style/TernaryParentheses:
  Enabled: true

Style/TrailingBodyOnClass:
  Enabled: true

Style/TrailingBodyOnMethodDefinition:
  Enabled: true

Style/TrailingBodyOnModule:
  Enabled: true

Style/TrailingMethodEndStatement:
  Enabled: true

Style/UnlessElse:
  Enabled: true

Style/YodaCondition:
  Enabled: true
